# Generated by Django 5.1.3 on 2025-02-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PRODUCT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_name', models.CharField(max_length=50)),
                ('P_category', models.CharField(max_length=50)),
                ('P_desc', models.TextField(max_length=500)),
            ],
        ),
    ]
