# Generated by Django 5.1.3 on 2025-02-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='P_desc',
            field=models.TextField(max_length=5000),
        ),
    ]
