# Generated by Django 5.1.3 on 2025-02-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_alter_product_p_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=20)),
                ('c_phone', models.IntegerField()),
                ('c_email', models.EmailField(max_length=254)),
                ('c_desc', models.TextField(max_length=500)),
            ],
        ),
    ]
