# Generated by Django 5.1.3 on 2025-02-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='p_sub',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='P_category',
            field=models.CharField(default='', max_length=50),
        ),
    ]
