# Generated by Django 5.1.3 on 2025-02-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_product_p_price_product_p_sub_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_image',
            field=models.ImageField(default='', upload_to='images/images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='P_category',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='P_name',
            field=models.CharField(max_length=100),
        ),
    ]
