# Generated by Django 5.1.3 on 2025-02-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_product_p_image_alter_product_p_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='p_image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
