# Generated by Django 5.1.3 on 2025-03-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0011_alter_orders_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='shipment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='tracking_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
