# Generated by Django 5.1.3 on 2025-04-24 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0012_orders_shipment_date_orders_tracking_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderupdate',
            name='order_id',
        ),
    ]
